# Generated by Django 6.0.3 on 2026-03-17 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_add_company"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contract_number", models.CharField(max_length=64, unique=True)),
                ("contract_date", models.DateField()),
                ("expiry_date", models.DateField()),
                ("duration_months", models.IntegerField(blank=True, null=True)),
                ("duration_years", models.IntegerField(blank=True, null=True)),
                ("status", models.CharField(default="draft", max_length=32)),
                ("license_type", models.CharField(blank=True, max_length=64)),
                ("billing_period", models.CharField(default="monthly", max_length=32)),
                (
                    "amount_per_month",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "amount_per_year",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("currency", models.CharField(default="BDT", max_length=3)),
                (
                    "total_contract_value",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                ("broadcast_message", models.TextField(blank=True)),
                ("payment_reminder_message", models.TextField(blank=True)),
                ("terms_and_conditions", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("auto_renewal", models.CharField(default="false", max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="api.company",
                    ),
                ),
            ],
            options={
                "db_table": "contract",
            },
        ),
    ]
