# Generated by Django 6.0.3 on 2026-03-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_add_contract"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="contact_person",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="company",
            name="payment_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="payment_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="payment_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="payment_type",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
