# Generated by Django 6.0.3 on 2026-03-18 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_add_company_payment_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Broadcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_id", models.IntegerField(blank=True, null=True)),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField(blank=True)),
                ("target", models.CharField(default="all", max_length=32)),
                ("is_active", models.BooleanField(default=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "broadcast",
            },
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bill_number", models.CharField(max_length=64)),
                ("bill_date", models.DateField()),
                ("due_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(default="draft", max_length=32)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "tax_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bills",
                        to="api.company",
                    ),
                ),
            ],
            options={
                "db_table": "bill",
            },
        ),
        migrations.CreateModel(
            name="ChartOfAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_code", models.CharField(max_length=64)),
                ("account_name", models.CharField(max_length=200)),
                ("account_type", models.CharField(max_length=32)),
                ("account_sub_type", models.CharField(blank=True, max_length=64)),
                ("description", models.TextField(blank=True)),
                (
                    "opening_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("opening_balance_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chart_of_accounts",
                        to="api.company",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="api.chartofaccount",
                    ),
                ),
            ],
            options={
                "db_table": "chart_of_account",
                "unique_together": {("company", "account_code")},
            },
        ),
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_name", models.CharField(max_length=200)),
                ("account_number", models.CharField(max_length=64)),
                ("bank_name", models.CharField(max_length=200)),
                ("account_type", models.CharField(default="CHECKING", max_length=32)),
                (
                    "opening_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("opening_balance_date", models.DateField(blank=True, null=True)),
                (
                    "current_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_accounts",
                        to="api.company",
                    ),
                ),
                (
                    "chart_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bank_accounts",
                        to="api.chartofaccount",
                    ),
                ),
            ],
            options={
                "db_table": "bank_account",
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_number", models.CharField(blank=True, max_length=64)),
                ("display_name", models.CharField(blank=True, max_length=200)),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("company_name", models.CharField(blank=True, max_length=200)),
                ("email", models.CharField(blank=True, max_length=150)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("billing_address_line1", models.CharField(blank=True, max_length=300)),
                ("billing_city", models.CharField(blank=True, max_length=100)),
                ("billing_state", models.CharField(blank=True, max_length=100)),
                ("billing_country", models.CharField(blank=True, max_length=100)),
                (
                    "opening_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("opening_balance_date", models.DateField(blank=True, null=True)),
                (
                    "current_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customers",
                        to="api.company",
                    ),
                ),
            ],
            options={
                "db_table": "customer",
            },
        ),
        migrations.CreateModel(
            name="FundTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("transfer_date", models.DateField()),
                ("reference", models.CharField(blank=True, max_length=200)),
                ("is_posted", models.BooleanField(default=False)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fund_transfers",
                        to="api.company",
                    ),
                ),
                (
                    "from_bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers_out",
                        to="api.bankaccount",
                    ),
                ),
                (
                    "to_bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers_in",
                        to="api.bankaccount",
                    ),
                ),
            ],
            options={
                "db_table": "fund_transfer",
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_number", models.CharField(max_length=64)),
                ("invoice_date", models.DateField()),
                ("due_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(default="draft", max_length=32)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "tax_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="api.company",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="api.customer",
                    ),
                ),
            ],
            options={
                "db_table": "invoice",
                "unique_together": {("company", "invoice_number")},
            },
        ),
        migrations.CreateModel(
            name="Island",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("island_code", models.CharField(blank=True, max_length=64)),
                ("island_name", models.CharField(max_length=200)),
                ("location_description", models.CharField(blank=True, max_length=300)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="islands",
                        to="api.company",
                    ),
                ),
            ],
            options={
                "db_table": "island",
            },
        ),
        migrations.CreateModel(
            name="Dispenser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dispenser_code", models.CharField(blank=True, max_length=64)),
                ("dispenser_name", models.CharField(max_length=200)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("serial_number", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispensers",
                        to="api.company",
                    ),
                ),
                (
                    "island",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispensers",
                        to="api.island",
                    ),
                ),
            ],
            options={
                "db_table": "dispenser",
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_number", models.CharField(blank=True, max_length=64)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("item_type", models.CharField(default="inventory", max_length=32)),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "quantity_on_hand",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                ("unit", models.CharField(default="piece", max_length=20)),
                ("pos_category", models.CharField(default="general", max_length=64)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("barcode", models.CharField(blank=True, max_length=64)),
                ("is_taxable", models.BooleanField(default=True)),
                ("is_pos_available", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("image_url", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="api.company",
                    ),
                ),
            ],
            options={
                "db_table": "item",
            },
        ),
        migrations.CreateModel(
            name="InvoiceLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=300)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=4, default=1, max_digits=14),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="api.invoice",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice_lines",
                        to="api.item",
                    ),
                ),
            ],
            options={
                "db_table": "invoice_line",
            },
        ),
        migrations.CreateModel(
            name="BillLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=300)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=4, default=1, max_digits=14),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="api.bill",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bill_lines",
                        to="api.item",
                    ),
                ),
            ],
            options={
                "db_table": "bill_line",
            },
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entry_number", models.CharField(blank=True, max_length=64)),
                ("entry_date", models.DateField()),
                ("description", models.TextField(blank=True)),
                ("is_posted", models.BooleanField(default=False)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_entries",
                        to="api.company",
                    ),
                ),
            ],
            options={
                "db_table": "journal_entry",
            },
        ),
        migrations.CreateModel(
            name="JournalEntryLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "debit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "credit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("description", models.CharField(blank=True, max_length=300)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_lines",
                        to="api.chartofaccount",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="api.journalentry",
                    ),
                ),
            ],
            options={
                "db_table": "journal_entry_line",
            },
        ),
        migrations.CreateModel(
            name="Meter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meter_code", models.CharField(blank=True, max_length=64)),
                ("meter_number", models.CharField(blank=True, max_length=64)),
                ("meter_name", models.CharField(blank=True, max_length=200)),
                (
                    "current_reading",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                ("last_reset_date", models.DateTimeField(blank=True, null=True)),
                ("reset_count", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meters",
                        to="api.company",
                    ),
                ),
                (
                    "dispenser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meters",
                        to="api.dispenser",
                    ),
                ),
            ],
            options={
                "db_table": "meter",
            },
        ),
        migrations.CreateModel(
            name="ShiftTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_templates",
                        to="api.company",
                    ),
                ),
            ],
            options={
                "db_table": "shift_template",
            },
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("station_number", models.CharField(blank=True, max_length=64)),
                ("station_name", models.CharField(max_length=200)),
                ("address_line1", models.CharField(blank=True, max_length=300)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stations",
                        to="api.company",
                    ),
                ),
            ],
            options={
                "db_table": "station",
            },
        ),
        migrations.CreateModel(
            name="ShiftSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opened_at", models.DateTimeField()),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("opened_by_user_id", models.IntegerField(blank=True, null=True)),
                ("closed_by_user_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_sessions",
                        to="api.company",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions",
                        to="api.shifttemplate",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shift_sessions",
                        to="api.station",
                    ),
                ),
            ],
            options={
                "db_table": "shift_session",
            },
        ),
        migrations.AddField(
            model_name="island",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="islands",
                to="api.station",
            ),
        ),
        migrations.CreateModel(
            name="SubscriptionLedgerInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_number", models.CharField(max_length=64)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("invoice_date", models.DateField()),
                ("due_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(default="draft", max_length=32)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_invoices",
                        to="api.company",
                    ),
                ),
            ],
            options={
                "db_table": "subscription_ledger_invoice",
            },
        ),
        migrations.CreateModel(
            name="Tank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tank_number", models.CharField(blank=True, max_length=64)),
                ("tank_name", models.CharField(max_length=200)),
                (
                    "capacity",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "current_stock",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "reorder_level",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                ("unit_of_measure", models.CharField(default="L", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tanks",
                        to="api.company",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tanks",
                        to="api.item",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tanks",
                        to="api.station",
                    ),
                ),
            ],
            options={
                "db_table": "tank",
            },
        ),
        migrations.CreateModel(
            name="Nozzle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nozzle_number", models.CharField(blank=True, max_length=64)),
                ("nozzle_code", models.CharField(blank=True, max_length=64)),
                ("nozzle_name", models.CharField(blank=True, max_length=200)),
                ("color_code", models.CharField(default="#3B82F6", max_length=20)),
                ("is_operational", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nozzles",
                        to="api.company",
                    ),
                ),
                (
                    "meter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nozzles",
                        to="api.meter",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nozzles",
                        to="api.item",
                    ),
                ),
                (
                    "tank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nozzles",
                        to="api.tank",
                    ),
                ),
            ],
            options={
                "db_table": "nozzle",
            },
        ),
        migrations.CreateModel(
            name="TankDip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dip_date", models.DateField()),
                (
                    "volume",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "water_level",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tank_dips",
                        to="api.company",
                    ),
                ),
                (
                    "tank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dips",
                        to="api.tank",
                    ),
                ),
            ],
            options={
                "db_table": "tank_dip",
            },
        ),
        migrations.CreateModel(
            name="Tax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(blank=True, max_length=300)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taxes",
                        to="api.company",
                    ),
                ),
            ],
            options={
                "db_table": "tax",
            },
        ),
        migrations.CreateModel(
            name="TaxRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rate", models.DecimalField(decimal_places=4, max_digits=6)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tax",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates",
                        to="api.tax",
                    ),
                ),
            ],
            options={
                "db_table": "tax_rate",
            },
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vendor_number", models.CharField(blank=True, max_length=64)),
                ("company_name", models.CharField(max_length=200)),
                ("display_name", models.CharField(blank=True, max_length=200)),
                ("contact_person", models.CharField(blank=True, max_length=200)),
                ("email", models.CharField(blank=True, max_length=150)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("billing_address_line1", models.CharField(blank=True, max_length=300)),
                (
                    "opening_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("opening_balance_date", models.DateField(blank=True, null=True)),
                (
                    "current_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendors",
                        to="api.company",
                    ),
                ),
            ],
            options={
                "db_table": "vendor",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_type", models.CharField(max_length=32)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("payment_date", models.DateField()),
                ("reference", models.CharField(blank=True, max_length=200)),
                ("memo", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bank_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="api.bankaccount",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="api.company",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="api.customer",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="api.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "payment",
            },
        ),
        migrations.AddField(
            model_name="bill",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bills",
                to="api.vendor",
            ),
        ),
        migrations.CreateModel(
            name="BroadcastRead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("read_at", models.DateTimeField(auto_now_add=True)),
                (
                    "broadcast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reads",
                        to="api.broadcast",
                    ),
                ),
            ],
            options={
                "db_table": "broadcast_read",
                "unique_together": {("user_id", "broadcast_id")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="bill",
            unique_together={("company", "bill_number")},
        ),
    ]
