# Generated by Django 5.2.12 on 2026-04-03 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_erp_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='invoice',
            name='shift_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='api.shiftsession'),
        ),
        migrations.AddField(
            model_name='shiftsession',
            name='cash_variance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='shiftsession',
            name='closing_cash_counted',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='shiftsession',
            name='expected_cash_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='shiftsession',
            name='opening_cash_float',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='shiftsession',
            name='sale_transaction_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shiftsession',
            name='total_sales_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.CreateModel(
            name='PaymentBillAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='api.bill')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_allocations', to='api.payment')),
            ],
            options={
                'db_table': 'payment_bill_allocation',
                'unique_together': {('payment', 'bill')},
            },
        ),
        migrations.CreateModel(
            name='PaymentInvoiceAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='api.invoice')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_allocations', to='api.payment')),
            ],
            options={
                'db_table': 'payment_invoice_allocation',
                'unique_together': {('payment', 'invoice')},
            },
        ),
    ]
