# Generated by Django 5.2.12 on 2026-04-05 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_employee_and_ledgers'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanCounterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=200)),
                ('role_type', models.CharField(default='other', help_text='bank, finance_company, individual, employee, vendor, customer, sister_concern, other', max_length=32)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.CharField(blank=True, max_length=150)),
                ('address', models.TextField(blank=True)),
                ('tax_id', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_counterparties', to='api.company')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_counterparties', to='api.customer')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_counterparties', to='api.employee')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_counterparties', to='api.vendor')),
            ],
            options={
                'db_table': 'loan_counterparty',
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_no', models.CharField(max_length=64)),
                ('direction', models.CharField(max_length=16)),
                ('status', models.CharField(default='draft', max_length=24)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('agreement_no', models.CharField(blank=True, max_length=120)),
                ('sanction_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('outstanding_principal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_disbursed', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_repaid_principal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('annual_interest_rate', models.DecimalField(blank=True, decimal_places=4, help_text='For schedules / accruals (Phase 2+).', max_digits=8, null=True)),
                ('term_months', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='api.company')),
                ('interest_account', models.ForeignKey(blank=True, help_text='Interest expense (borrowed) or interest income (lent).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_interest', to='api.chartofaccount')),
                ('principal_account', models.ForeignKey(help_text='Loan payable (borrowed) or loans receivable (lent) GL line.', on_delete=django.db.models.deletion.PROTECT, related_name='loans_principal', to='api.chartofaccount')),
                ('settlement_account', models.ForeignKey(help_text='Bank/cash chart line used for disbursement and repayments.', on_delete=django.db.models.deletion.PROTECT, related_name='loans_settlement', to='api.chartofaccount')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='api.loancounterparty')),
            ],
            options={
                'db_table': 'loan',
                'unique_together': {('company', 'loan_no')},
            },
        ),
        migrations.CreateModel(
            name='LoanDisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disbursement_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference', models.CharField(blank=True, max_length=200)),
                ('memo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_disbursements', to='api.journalentry')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='api.loan')),
            ],
            options={
                'db_table': 'loan_disbursement',
            },
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repayment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('principal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('interest_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('reference', models.CharField(blank=True, max_length=200)),
                ('memo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_repayments', to='api.journalentry')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='api.loan')),
            ],
            options={
                'db_table': 'loan_repayment',
            },
        ),
    ]
