# Generated by Django 5.2.12 on 2026-04-06 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_loan_banking_product_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='interest_accrual_account',
            field=models.ForeignKey(blank=True, help_text='Accrued interest payable (borrowed: liability) or accrued interest receivable (lent: asset).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_interest_accrual', to='api.chartofaccount'),
        ),
        migrations.AddField(
            model_name='loan',
            name='islamic_contract_variant',
            field=models.CharField(blank=True, default='', help_text='Optional label when banking_model is islamic (murabaha, ijara, etc.); same GL mechanics.', max_length=24),
        ),
        migrations.CreateModel(
            name='LoanInterestAccrual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accrual_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('days_basis', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('memo', models.TextField(blank=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_interest_accruals', to='api.journalentry')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_accruals', to='api.loan')),
                ('reversal_journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_interest_accrual_reversals', to='api.journalentry')),
            ],
            options={
                'db_table': 'loan_interest_accrual',
                'ordering': ['-accrual_date', '-id'],
            },
        ),
    ]
