# Generated by Django 5.2.12 on 2026-04-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_loan_annual_interest_rate_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='tankdip',
            name='book_stock_before',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
    ]
