# Generated by Django 5.2.12 on 2026-04-07 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_customer_vendor_bank_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_number', models.CharField(blank=True, max_length=64)),
                ('deposit_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('memo', models.TextField(blank=True)),
                ('is_reconciled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_deposits', to='api.bankaccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_deposits', to='api.company')),
            ],
            options={
                'db_table': 'bank_deposit',
                'ordering': ['-deposit_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='bank_deposit',
            field=models.ForeignKey(blank=True, help_text='When set, this receipt was included in a batch bank deposit (undeposited → bank).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_payments', to='api.bankdeposit'),
        ),
    ]
