# Generated by Django 4.2.30 on 2026-04-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_company_subscription_cancel_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='platform_release',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='company',
            name='platform_release_applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
