# Generated by Django 4.2.30 on 2026-04-18 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_tenant_platform_release_event'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tenantplatformreleaseevent',
            new_name='tenant_plat_company_c92b91_idx',
            old_name='tenant_plat_company_4376c6_idx',
        ),
    ]
