# Generated by Django 4.2.30 on 2026-04-22 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_company_code_master_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrun',
            name='salary_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_runs', to='api.journalentry'),
        ),
    ]
