# Generated by Django 4.2.30 on 2026-04-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_payroll_salary_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftsession',
            name='employee_schedule',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='shiftsession',
            name='opening_meters',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
