# Generated by Django — align is_active with is_operational (single source of truth: operational for POS)

from django.db import migrations
from django.db.models import F


def sync_nozzle_is_active(apps, schema_editor):
    Nozzle = apps.get_model("api", "Nozzle")
    Nozzle.objects.update(is_active=F("is_operational"))


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0039_loan_counterparty_opening_ledger"),
    ]

    operations = [
        migrations.RunPython(sync_nozzle_is_active, noop_reverse),
    ]
