# Generated by Django — User.pos_sale_scope for cashier POS line types

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0040_sync_nozzle_is_active_with_is_operational"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pos_sale_scope",
            field=models.CharField(default="both", max_length=16),
        ),
    ]
