# Generated by Django 5.2.13 on 2026-04-29 06:08

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def _backfill_station_stock(apps, schema_editor):
    Company = apps.get_model("api", "Company")
    Station = apps.get_model("api", "Station")
    Item = apps.get_model("api", "Item")
    Tank = apps.get_model("api", "Tank")
    ItemStationStock = apps.get_model("api", "ItemStationStock")
    for co in Company.objects.all().order_by("id"):
        st_list = list(Station.objects.filter(company_id=co.id, is_active=True).order_by("id"))
        if not st_list:
            s = Station(
                company_id=co.id,
                station_name="Default",
                is_active=True,
            )
            s.save()
            st_list = [s]
        first = st_list[0]
        for it in Item.objects.filter(company_id=co.id).order_by("id"):
            if Tank.objects.filter(company_id=co.id, product_id=it.id).exists():
                continue
            itype = (it.item_type or "").strip().lower()
            if itype in ("non_inventory", "non-inventory", "service"):
                continue
            q = it.quantity_on_hand
            if q is None:
                q = Decimal("0")
            ItemStationStock.objects.get_or_create(
                company_id=co.id,
                station_id=first.id,
                item_id=it.id,
                defaults={"quantity": q},
            )


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_payroll_run_earning_components'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='receipt_station',
            field=models.ForeignKey(blank=True, help_text="Shop (non-tank) inventory from this bill is received into this station's stock.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills_receipts', to='api.station'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='station',
            field=models.ForeignKey(blank=True, help_text='Selling location: ties sales and shop COGS to a station for reporting.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='api.station'),
        ),
        migrations.CreateModel(
            name='InventoryTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_number', models.CharField(blank=True, max_length=64)),
                ('transfer_date', models.DateField()),
                ('status', models.CharField(default='draft', max_length=16)),
                ('memo', models.CharField(blank=True, max_length=500)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_transfers', to='api.company')),
                ('from_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transfers_out', to='api.station')),
                ('to_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transfers_in', to='api.station')),
            ],
            options={
                'db_table': 'inventory_transfer',
                'ordering': ['-transfer_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransferLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transfer_lines', to='api.item')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='api.inventorytransfer')),
            ],
            options={
                'db_table': 'inventory_transfer_line',
            },
        ),
        migrations.CreateModel(
            name='ItemStationStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_station_stocks', to='api.company')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_stocks', to='api.item')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_stocks', to='api.station')),
            ],
            options={
                'db_table': 'item_station_stock',
                'indexes': [models.Index(fields=['company', 'item'], name='item_statio_company_a06e2a_idx')],
                'unique_together': {('station', 'item')},
            },
        ),
        migrations.RunPython(_backfill_station_stock, _noop_reverse),
    ]
