# Generated by Django for Company.time_zone (IANA, default Asia/Dhaka)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0047_multi_site_masters_payments"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="time_zone",
            field=models.CharField(
                default="Asia/Dhaka",
                help_text="IANA time zone (e.g. Asia/Dhaka) for business date and local time display.",
                max_length=64,
            ),
        ),
    ]
