# Generated by Django 5.2.13 on 2026-04-30 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_journal_entry_line_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='station_mode',
            field=models.CharField(default='multi', help_text='single = at most one active station (inactive rows allowed); multi = multiple stations (default).', max_length=16),
        ),
        migrations.AlterField(
            model_name='payrollrun',
            name='station',
            field=models.ForeignKey(blank=True, help_text='Optional: attribute this run to one site (management / job-cost reporting; GL still company-level).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_runs', to='api.station'),
        ),
    ]
