# Generated by Django 5.2.13 on 2026-05-01 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_company_station_mode_default_single'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='aquaculture_enabled',
            field=models.BooleanField(default=False, help_text='When true, tenant may use Aquaculture (ponds, pond P&L, payroll pond splits). Hidden for fuel-only subscribers by default.'),
        ),
        migrations.CreateModel(
            name='AquaculturePond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, help_text='Short code for reports (optional).', max_length=64)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aquaculture_ponds', to='api.company')),
            ],
            options={
                'db_table': 'aquaculture_pond',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AquacultureFishSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(db_index=True)),
                ('weight_kg', models.DecimalField(decimal_places=4, max_digits=14)),
                ('fish_count', models.IntegerField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('buyer_name', models.CharField(blank=True, max_length=200)),
                ('memo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aquaculture_fish_sales', to='api.company')),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fish_sales', to='api.aquaculturepond')),
            ],
            options={
                'db_table': 'aquaculture_fish_sale',
                'ordering': ['-sale_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AquacultureExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_category', models.CharField(db_index=True, max_length=64)),
                ('expense_date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('memo', models.TextField(blank=True)),
                ('vendor_name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aquaculture_expenses', to='api.company')),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='api.aquaculturepond')),
            ],
            options={
                'db_table': 'aquaculture_expense',
                'ordering': ['-expense_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AquacultureBiomassSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_date', models.DateField(db_index=True)),
                ('estimated_fish_count', models.IntegerField(blank=True, null=True)),
                ('estimated_total_weight_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('avg_weight_kg', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aquaculture_biomass_samples', to='api.company')),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biomass_samples', to='api.aquaculturepond')),
            ],
            options={
                'db_table': 'aquaculture_biomass_sample',
                'ordering': ['-sample_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRunPondAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pond_allocations', to='api.payrollrun')),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_allocations', to='api.aquaculturepond')),
            ],
            options={
                'db_table': 'payroll_run_pond_allocation',
            },
        ),
        migrations.AddIndex(
            model_name='aquaculturepond',
            index=models.Index(fields=['company', 'is_active'], name='aquaculture_company_5da2fa_idx'),
        ),
        migrations.AddIndex(
            model_name='aquaculturefishsale',
            index=models.Index(fields=['company', 'pond', 'sale_date'], name='aquaculture_company_c2b564_idx'),
        ),
        migrations.AddIndex(
            model_name='aquacultureexpense',
            index=models.Index(fields=['company', 'pond', 'expense_date'], name='aquaculture_company_1a2f6f_idx'),
        ),
        migrations.AddIndex(
            model_name='aquaculturebiomasssample',
            index=models.Index(fields=['company', 'pond', 'sample_date'], name='aquaculture_company_4839b6_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollrunpondallocation',
            index=models.Index(fields=['pond'], name='payroll_run_pond_id_0d4b5d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollrunpondallocation',
            unique_together={('payroll_run', 'pond')},
        ),
    ]
