# Generated by Django 5.x — aquaculture pond: leasing vs water area and depth

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0075_station_operates_fuel_retail"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aquaculturepond",
            old_name="pond_size_decimal",
            new_name="leasing_area_decimal",
        ),
        migrations.AlterField(
            model_name="aquaculturepond",
            name="leasing_area_decimal",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Leased land area in decimals — used with lease price per decimal for landlord rent.",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="aquaculturepond",
            name="water_area_decimal",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Effective water surface area in decimals — for stocking, density, and production planning.",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="aquaculturepond",
            name="pond_depth_ft",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text=(
                    "Representative average depth in feet — with water area (decimals) uses "
                    "435.6 sq ft per decimal for volume."
                ),
                max_digits=10,
                null=True,
            ),
        ),
    ]
