# Generated by Django 5.2.13 on 2026-05-16 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0095_aquaculture_expense_inventory_line"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantReportingCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "application",
                    models.CharField(
                        choices=[("aquaculture", "Aquaculture"), ("fuel_station", "Fuel station")],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("expense", "Expense"), ("income", "Income")],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Stable key stored on transactions (aquaculture) or shown in pickers.",
                        max_length=64,
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                (
                    "maps_to_code",
                    models.CharField(
                        help_text="Built-in aquaculture code, or fuel-station rollup key, used for GL / bucket logic.",
                        max_length=64,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_reporting_categories",
                        to="api.company",
                    ),
                ),
            ],
            options={
                "db_table": "tenant_reporting_category",
                "ordering": ["application", "kind", "sort_order", "code"],
            },
        ),
        migrations.AddField(
            model_name="journalentryline",
            name="tenant_reporting_category",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional tenant-defined fuel-station reporting tag on manual journal lines.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="journal_lines",
                to="api.tenantreportingcategory",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantreportingcategory",
            constraint=models.UniqueConstraint(
                fields=("company", "application", "kind", "code"),
                name="tenant_reporting_cat_company_app_kind_code_uniq",
            ),
        ),
    ]
