# Generated by Django 5.2.13 on 2026-05-16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0096_tenant_reporting_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="billline",
            name="fuel_station_expense_category",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Fuel-station expense rollup or tenant category code (station P&L on bills).",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="billline",
            name="tenant_reporting_category",
            field=models.ForeignKey(
                blank=True,
                help_text="Resolved tenant fuel-station reporting row when fuel_station_expense_category is custom.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bill_lines",
                to="api.tenantreportingcategory",
            ),
        ),
        migrations.AddField(
            model_name="journalentryline",
            name="fuel_station_expense_rollup",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Built-in fuel-station expense rollup when no tenant_reporting_category FK is set.",
                max_length=64,
            ),
        ),
    ]
