# Generated by Django 5.2.14 on 2026-05-31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0119_item_opening_stock_gl'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRestoreAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, help_text='backup_download | restore', max_length=32)),
                ('success', models.BooleanField(default=True)),
                ('actor_user_id', models.IntegerField(blank=True, null=True)),
                ('actor_label', models.CharField(blank=True, default='', max_length=255)),
                ('source', models.CharField(blank=True, default='', help_text='tenant | admin', max_length=48)),
                ('ip_address', models.CharField(blank=True, default='', max_length=64)),
                ('record_count', models.IntegerField(blank=True, null=True)),
                ('bytes_size', models.BigIntegerField(blank=True, null=True)),
                ('safety_snapshot_path', models.CharField(blank=True, default='', max_length=1024)),
                ('error_message', models.TextField(blank=True)),
                ('detail', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_restore_audits', to='api.company')),
            ],
            options={
                'db_table': 'backup_restore_audit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='backuprestoreaudit',
            index=models.Index(fields=['company', '-created_at'], name='backup_rest_company_438581_idx'),
        ),
    ]
