# Generated by Django 5.2.6 on 2026-06-18 21:03
#
# Index renames and help_text-only field tweaks — no database DDL required.
# Autogenerated RenameIndex ops fail when SQLite/PostgreSQL index names already
# match Django's auto names (see aq_db_close_co_pond_end_idx missing on dev DB).

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0138_payroll_run_employee_allocation'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name='aquaculturedatabankpondclose',
                    new_name='aquaculture_company_ea4b73_idx',
                    old_name='aq_db_close_co_pond_end_idx',
                ),
                migrations.RenameIndex(
                    model_name='aquaculturedatabankpondclose',
                    new_name='aquaculture_pond_id_ff59a8_idx',
                    old_name='aq_db_close_pond_lock_idx',
                ),
                migrations.RenameIndex(
                    model_name='aquacultureexpense',
                    new_name='aquaculture_company_a34372_idx',
                    old_name='aquaculture_company_exp_date_idx',
                ),
                migrations.RenameIndex(
                    model_name='aquaculturefinancingallocation',
                    new_name='aquaculture_company_de34e6_idx',
                    old_name='aq_fin_alloc_co_loan_dt',
                ),
                migrations.RenameIndex(
                    model_name='aquaculturefinancingallocation',
                    new_name='aquaculture_company_2f8bfd_idx',
                    old_name='aq_fin_alloc_co_pond_dt',
                ),
                migrations.RenameIndex(
                    model_name='aquaculturefishpondtransfer',
                    new_name='aquaculture_company_5053dc_idx',
                    old_name='aquaculture_company_8a1c2d_idx',
                ),
                migrations.RenameIndex(
                    model_name='aquaculturefishpondtransferline',
                    new_name='aquaculture_to_pond_60fab9_idx',
                    old_name='aquaculture_to_pond_9b3e4f_idx',
                ),
                migrations.RenameIndex(
                    model_name='aquaculturefishsale',
                    new_name='aquaculture_company_6f6ef2_idx',
                    old_name='aquaculture_company_9d2b3f_idx',
                ),
                migrations.RenameIndex(
                    model_name='aquaculturefishstockledger',
                    new_name='aquaculture_company_5210b8_idx',
                    old_name='aquaculture_fishstk_co_pond_dt',
                ),
                migrations.RenameIndex(
                    model_name='aquaculturelandlord',
                    new_name='aquaculture_company_c0a0de_idx',
                    old_name='aquaculture_company_2f7e2d_idx',
                ),
                migrations.RenameIndex(
                    model_name='aquaculturelandlordledgerentry',
                    new_name='aquaculture_landlor_8dc304_idx',
                    old_name='aquaculture_landlord_e3f4_idx',
                ),
                migrations.RenameIndex(
                    model_name='aquaculturelandlordpondshare',
                    new_name='aquaculture_pond_id_638fd7_idx',
                    old_name='aquaculture_pond_id_0a8b1c_idx',
                ),
                migrations.RenameIndex(
                    model_name='aquaculturepondplopening',
                    new_name='aquaculture_company_24ebc3_idx',
                    old_name='aq_pl_ob_co_pond_kind',
                ),
                migrations.RenameIndex(
                    model_name='aquaculturepondprofittransfer',
                    new_name='aquaculture_company_3d9c51_idx',
                    old_name='aquaculture_company_0f90b8_idx',
                ),
                migrations.RenameIndex(
                    model_name='aquacultureproductioncycle',
                    new_name='aquaculture_company_d6b99f_idx',
                    old_name='aquaculture_company_8c1a2e_idx',
                ),
                migrations.RenameIndex(
                    model_name='aquaculturewarehousegroup',
                    new_name='aquaculture_company_cdfe96_idx',
                    old_name='aquaculture_company_8e2f1a_idx',
                ),
                migrations.RenameIndex(
                    model_name='itempondstock',
                    new_name='item_pond_s_company_027116_idx',
                    old_name='api_itempon_company_2f8b2d_idx',
                ),
                migrations.RenameIndex(
                    model_name='passwordresettoken',
                    new_name='password_re_user_id_145056_idx',
                    old_name='pwreset_user_used_idx',
                ),
                migrations.RenameIndex(
                    model_name='passwordresettoken',
                    new_name='password_re_expires_214fae_idx',
                    old_name='pwreset_expires_idx',
                ),
                migrations.RenameIndex(
                    model_name='payrollrunemployeeallocation',
                    new_name='payroll_run_employe_3ee3c7_idx',
                    old_name='payroll_run_emp_id_idx',
                ),
                migrations.RenameIndex(
                    model_name='pondwarehouseinterpondtransfer',
                    new_name='pond_wareho_company_86ce21_idx',
                    old_name='pond_wh_ip_from_idx',
                ),
                migrations.RenameIndex(
                    model_name='pondwarehouseinterpondtransfer',
                    new_name='pond_wareho_company_8307ec_idx',
                    old_name='pond_wh_ip_to_idx',
                ),
                migrations.AlterField(
                    model_name='aquaculturebiomasssample',
                    name='biomass_gain_kg',
                    field=models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text='(sample mean − reference mean) × reference head; may be negative.',
                        max_digits=14,
                        null=True,
                    ),
                ),
                migrations.AlterField(
                    model_name='aquaculturebiomasssample',
                    name='extrapolated_biomass_kg',
                    field=models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text='Sample mean × reference head count (estimated pond biomass).',
                        max_digits=14,
                        null=True,
                    ),
                ),
                migrations.AlterField(
                    model_name='aquaculturebiomasssample',
                    name='fish_species',
                    field=models.CharField(
                        db_index=True,
                        default='tilapia',
                        help_text='Species this biomass estimate refers to (polyculture).',
                        max_length=64,
                    ),
                ),
                migrations.AlterField(
                    model_name='aquaculturebiomasssample',
                    name='stock_reference_avg_weight_kg',
                    field=models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text='Reference mean kg/fish = net kg ÷ head when both positive.',
                        max_digits=14,
                        null=True,
                    ),
                ),
                migrations.AlterField(
                    model_name='aquaculturebiomasssample',
                    name='stock_reference_fish_count',
                    field=models.IntegerField(
                        blank=True,
                        help_text='Implied net head from stock movements (Fish stock basis), snapshot at save.',
                        null=True,
                    ),
                ),
                migrations.AlterField(
                    model_name='aquaculturebiomasssample',
                    name='stock_reference_net_weight_kg',
                    field=models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text='Implied net biological kg for this species, snapshot at save.',
                        max_digits=14,
                        null=True,
                    ),
                ),
                migrations.AlterField(
                    model_name='aquaculturefinancingallocation',
                    name='allocation_kind',
                    field=models.CharField(default='use', max_length=16),
                ),
                migrations.AlterField(
                    model_name='aquaculturefinancingallocation',
                    name='amount',
                    field=models.DecimalField(decimal_places=2, max_digits=14),
                ),
                migrations.AlterField(
                    model_name='aquaculturepond',
                    name='lease_paid_to_landlord',
                    field=models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text='Cumulative cash/rent paid to the landlord for this pond lease.',
                        max_digits=18,
                    ),
                ),
                migrations.AlterField(
                    model_name='billline',
                    name='aquaculture_fish_count',
                    field=models.IntegerField(
                        blank=True,
                        help_text='For fish-type items: total headcount on this line (optional).',
                        null=True,
                    ),
                ),
                migrations.AlterField(
                    model_name='billline',
                    name='aquaculture_fish_weight_kg',
                    field=models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text='For fish-type items (Item.pos_category=fish): total weight (kg) on this line (optional).',
                        max_digits=14,
                        null=True,
                    ),
                ),
                migrations.AlterField(
                    model_name='billline',
                    name='expense_account',
                    field=models.ForeignKey(
                        blank=True,
                        help_text='Optional expense/COGS-side debit for this line; overrides item and vendor defaults.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='bill_lines_expense_override',
                        to='api.chartofaccount',
                    ),
                ),
                migrations.AlterField(
                    model_name='company',
                    name='aquaculture_enabled',
                    field=models.BooleanField(
                        default=False,
                        help_text='When true (and typically aquaculture_licensed), tenant Admin may use Aquaculture in ERP (menu, APIs).',
                    ),
                ),
                migrations.AlterField(
                    model_name='company',
                    name='aquaculture_licensed',
                    field=models.BooleanField(
                        default=False,
                        help_text='SaaS: new license grants enable Aquaculture in ERP; tenant Admin may turn aquaculture_enabled off in Company settings.',
                    ),
                ),
                migrations.AlterField(
                    model_name='employee',
                    name='aquaculture_labor_scope',
                    field=models.CharField(
                        choices=[
                            ('not_applicable', 'Not applicable (site / company payroll)'),
                            ('assigned_pond', 'Single pond'),
                            ('all_ponds_equal', 'Shared equally across all ponds'),
                        ],
                        db_index=True,
                        default='not_applicable',
                        help_text='not_applicable: fuel forecourt, admin, shop staff — wages are not split to pond P&L. assigned_pond: field / pond worker — wages to home pond (or shop site default when set). all_ponds_equal: shared aquaculture managers — salary split evenly on all active ponds.',
                        max_length=32,
                    ),
                ),
                migrations.AlterField(
                    model_name='fixedasset',
                    name='accumulated_depreciation',
                    field=models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text='Running total posted to accumulated depreciation (includes opening balance).',
                        max_digits=14,
                    ),
                ),
                migrations.AlterField(
                    model_name='fixedasset',
                    name='opening_accumulated_depreciation',
                    field=models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text='Already-depreciated amount when adopting an asset mid-life (no acquisition JE).',
                        max_digits=14,
                    ),
                ),
                migrations.AlterField(
                    model_name='invoiceline',
                    name='revenue_account',
                    field=models.ForeignKey(
                        blank=True,
                        help_text='Optional revenue GL for this line; overrides item-level revenue and template splits.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='invoice_lines_revenue_override',
                        to='api.chartofaccount',
                    ),
                ),
                migrations.AlterField(
                    model_name='item',
                    name='cogs_account',
                    field=models.ForeignKey(
                        blank=True,
                        help_text='When set, COGS for this SKU uses this account instead of template COGS codes.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='items_default_cogs',
                        to='api.chartofaccount',
                    ),
                ),
                migrations.AlterField(
                    model_name='item',
                    name='expense_account',
                    field=models.ForeignKey(
                        blank=True,
                        help_text='When set, non-inventory vendor bill lines for this SKU debit this expense (else office default).',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='items_default_expense',
                        to='api.chartofaccount',
                    ),
                ),
                migrations.AlterField(
                    model_name='item',
                    name='inventory_account',
                    field=models.ForeignKey(
                        blank=True,
                        help_text='When set, inventory receipt/sale GL for this SKU uses this asset account instead of 1200/1220.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='items_default_inventory',
                        to='api.chartofaccount',
                    ),
                ),
                migrations.AlterField(
                    model_name='item',
                    name='revenue_account',
                    field=models.ForeignKey(
                        blank=True,
                        help_text='When set, invoice/POS revenue for this SKU posts here instead of template fuel/shop revenue codes.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='items_default_revenue',
                        to='api.chartofaccount',
                    ),
                ),
                migrations.AlterField(
                    model_name='loan',
                    name='aquaculture_financing',
                    field=models.BooleanField(
                        default=False,
                        help_text='Whole-aquaculture working-capital loan; shown on Aquaculture → Financing with pond allocation and repayment worksheet.',
                    ),
                ),
                migrations.AlterField(
                    model_name='organization',
                    name='custom_domain',
                    field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
                ),
                migrations.AlterField(
                    model_name='payrollrun',
                    name='salary_expense_account',
                    field=models.ForeignKey(
                        blank=True,
                        help_text='When set, posted salary journals debit this expense instead of template 6400.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='payroll_runs_salary_expense',
                        to='api.chartofaccount',
                    ),
                ),
                migrations.AlterField(
                    model_name='shiftsession',
                    name='closing_meters',
                    field=models.JSONField(blank=True, default=list),
                ),
                migrations.AlterField(
                    model_name='station',
                    name='operates_fuel_retail',
                    field=models.BooleanField(
                        default=True,
                        help_text='Fuel forecourt site (tanks, islands, nozzles). False for aquaculture/shop-only hubs without underground fuel.',
                    ),
                ),
                migrations.AlterField(
                    model_name='vendor',
                    name='default_expense_account',
                    field=models.ForeignKey(
                        blank=True,
                        help_text='Default expense debit for vendor bill lines without an item or without a line-level GL override.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='vendors_default_expense',
                        to='api.chartofaccount',
                    ),
                ),
            ],
        ),
    ]
