# Generated by Django 5.2.13 on 2026-06-19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0139_rename_aq_db_close_co_pond_end_idx_aquaculture_company_ea4b73_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantreportingcategory",
            name="aquaculture_pond",
            field=models.ForeignKey(
                blank=True,
                help_text="When set, category applies only to this pond. Null = all ponds in application.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tenant_reporting_categories",
                to="api.aquaculturepond",
            ),
        ),
        migrations.AddField(
            model_name="tenantreportingcategory",
            name="station",
            field=models.ForeignKey(
                blank=True,
                help_text="When set, category applies only to this station. Null = all stations in application.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tenant_reporting_categories",
                to="api.station",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantreportingcategory",
            constraint=models.CheckConstraint(
                check=~models.Q(("station__isnull", False), ("aquaculture_pond__isnull", False)),
                name="tenant_reporting_cat_station_pond_mutually_exclusive",
            ),
        ),
    ]
