# Generated by Django 5.2.13 on 2026-06-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0140_tenant_reporting_category_entity"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantreportingcategory",
            name="head_office_only",
            field=models.BooleanField(
                default=False,
                help_text="When true, category applies only to head office (no station or pond tag).",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantreportingcategory",
            constraint=models.CheckConstraint(
                check=~models.Q(("head_office_only", True), ("station__isnull", False)),
                name="tenant_reporting_cat_ho_not_with_station",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantreportingcategory",
            constraint=models.CheckConstraint(
                check=~models.Q(("head_office_only", True), ("aquaculture_pond__isnull", False)),
                name="tenant_reporting_cat_ho_not_with_pond",
            ),
        ),
    ]
