# Generated by Django 5.2.6 on 2026-06-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0141_tenant_reporting_category_head_office'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tenantreportingcategory',
            name='tenant_reporting_cat_station_pond_mutually_exclusive',
        ),
        migrations.RemoveConstraint(
            model_name='tenantreportingcategory',
            name='tenant_reporting_cat_ho_not_with_pond',
        ),
        migrations.AddConstraint(
            model_name='tenantreportingcategory',
            constraint=models.CheckConstraint(condition=models.Q(('aquaculture_pond__isnull', False), ('station__isnull', False), _negated=True), name='tenant_reporting_cat_station_pond_mutually_exclusive'),
        ),
        migrations.AddConstraint(
            model_name='tenantreportingcategory',
            constraint=models.CheckConstraint(condition=models.Q(('aquaculture_pond__isnull', False), ('head_office_only', True), _negated=True), name='tenant_reporting_cat_ho_not_with_pond'),
        ),
    ]
