# Generated by Django 5.2.13 on 2026-06-19

from django.db import migrations


def seed_cross_entity_expense_categories(apps, schema_editor):
    Company = apps.get_model("api", "Company")
    from api.services.tenant_reporting_categories import ensure_cross_entity_expense_categories

    for cid in Company.objects.filter(is_deleted=False).values_list("id", flat=True):
        ensure_cross_entity_expense_categories(int(cid))


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0142_remove_tenantreportingcategory_tenant_reporting_cat_station_pond_mutually_exclusive_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_cross_entity_expense_categories, migrations.RunPython.noop),
    ]
