# Generated by Django 5.2.15 on 2026-07-04 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0157_payment_idempotency_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='brain_plan',
            field=models.CharField(default='free', help_text='Company Brain tier: free (ERP rules + limited chat), growth, enterprise (LLM + web research).', max_length=16),
        ),
        migrations.CreateModel(
            name='BrainConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('context_entity_type', models.CharField(blank=True, default='', help_text='Optional focus: station, pond, employee, company.', max_length=32)),
                ('context_entity_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brain_conversations', to='api.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brain_conversations', to='api.user')),
            ],
            options={
                'db_table': 'brain_conversation',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BrainMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=16)),
                ('content', models.TextField(help_text='User text or assistant answer (Bangla by default).')),
                ('structured', models.JSONField(blank=True, default=dict, help_text='reasoning_steps_bn, sources, confidence, missing_inputs, suggested_actions.')),
                ('model_used', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.brainconversation')),
            ],
            options={
                'db_table': 'brain_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='brainconversation',
            index=models.Index(fields=['company', '-updated_at'], name='brain_conve_company_cde596_idx'),
        ),
        migrations.AddIndex(
            model_name='brainmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='brain_messa_convers_3991d8_idx'),
        ),
    ]
