# Generated by Django 5.2.15 on 2026-07-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0163_brain_handover_documents'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='brainactionlog',
            new_name='brain_actio_company_552eb9_idx',
            old_name='brain_action_company_created_idx',
        ),
        migrations.RenameIndex(
            model_name='braincompanydocument',
            new_name='brain_compa_company_077593_idx',
            old_name='brain_doc_co_active_idx',
        ),
        migrations.RenameIndex(
            model_name='braininsight',
            new_name='brain_insig_company_d7d5a8_idx',
            old_name='brain_insight_company_created_idx',
        ),
        migrations.RenameIndex(
            model_name='braininsight',
            new_name='brain_insig_company_00dd31_idx',
            old_name='brain_insight_company_dismiss_idx',
        ),
        migrations.RenameIndex(
            model_name='brainprediction',
            new_name='brain_predi_company_4997db_idx',
            old_name='brain_pred_company_created_idx',
        ),
        migrations.RenameIndex(
            model_name='brainprediction',
            new_name='brain_predi_company_ba7c31_idx',
            old_name='brain_pred_company_type_idx',
        ),
        migrations.RenameIndex(
            model_name='brainusagelog',
            new_name='brain_usage_company_2154cd_idx',
            old_name='brain_usage_company_created_idx',
        ),
        migrations.RenameIndex(
            model_name='brainusagelog',
            new_name='brain_usage_company_5f116a_idx',
            old_name='brain_usage_company_date_idx',
        ),
        migrations.RenameIndex(
            model_name='employeehandoverprofile',
            new_name='employee_ha_company_0b7fd9_idx',
            old_name='handover_co_status_idx',
        ),
        migrations.RenameIndex(
            model_name='employeehandoverprofile',
            new_name='employee_ha_company_1681be_idx',
            old_name='handover_co_emp_idx',
        ),
        migrations.RenameIndex(
            model_name='employeehandoverprofile',
            new_name='employee_ha_company_009f3f_idx',
            old_name='handover_co_title_idx',
        ),
        migrations.AlterField(
            model_name='braincompanydocument',
            name='role_tags',
            field=models.JSONField(blank=True, default=list, help_text='Lowercase role keywords e.g. accountant, pond supervisor.'),
        ),
        migrations.AlterField(
            model_name='employeehandoverprofile',
            name='contacts_and_channels',
            field=models.JSONField(blank=True, default=list, help_text='e.g. [{"type":"whatsapp","label":"Pond ops","value":"..."}]'),
        ),
        migrations.AlterField(
            model_name='employeehandoverprofile',
            name='is_current_for_role',
            field=models.BooleanField(default=True, help_text='Latest published handover for this job title (when set).'),
        ),
    ]
