# Generated by Django 5.2.15 on 2026-08-19 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0166_company_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='aquaculturepond',
            name='auto_internal_vendor',
            field=models.BooleanField(default=False, help_text='When true, internal_vendor was created for this pond; name and active flag sync from pond.'),
        ),
        migrations.AddField(
            model_name='aquaculturepond',
            name='internal_vendor',
            field=models.ForeignKey(blank=True, help_text="Supplier identity of this pond when it sells fish or fingerlings to another pond; the buying pond's bill is raised against this vendor.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aquaculture_ponds_internal', to='api.vendor'),
        ),
        migrations.AddField(
            model_name='customer',
            name='internal_pond',
            field=models.ForeignKey(blank=True, help_text='Pond this internal party stands for; set only when is_internal is true.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_customers', to='api.aquaculturepond'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_internal',
            field=models.BooleanField(db_index=True, default=False, help_text='Internal trading party representing another profit centre of this company (e.g. an aquaculture pond). Excluded from external A/R-A/P totals and eliminated on consolidation.'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='internal_pond',
            field=models.ForeignKey(blank=True, help_text='Pond this internal party stands for; set only when is_internal is true.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_vendors', to='api.aquaculturepond'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_internal',
            field=models.BooleanField(db_index=True, default=False, help_text='Internal trading party representing another profit centre of this company (e.g. an aquaculture pond). Excluded from external A/R-A/P totals and eliminated on consolidation.'),
        ),
    ]
