# Generated by Django 5.2.15 on 2026-08-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0168_backfill_pond_internal_vendors'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccount',
            name='note',
            field=models.CharField(blank=True, default='', help_text='Short internal note about this account (not shown on statements).', max_length=500),
        ),
    ]
