# Generated by Django 5.2.15 on 2026-08-19 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0169_chart_account_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='aquaculturebiomasssample',
            name='sample_time',
            field=models.TimeField(blank=True, help_text='Clock time for this sampling. Auto rows carry the entry time of the bill / transfer / sale they came from, so several trades on one date stay in order.', null=True),
        ),
        migrations.AddField(
            model_name='aquaculturebiomasssample',
            name='source_bill_line',
            field=models.OneToOneField(blank=True, help_text='When set, auto-created from that fish/fry purchase line on a posted vendor bill (buying pond).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biomass_sample_from_bill_line', to='api.billline'),
        ),
        migrations.AddField(
            model_name='aquaculturebiomasssample',
            name='source_fish_pond_transfer',
            field=models.OneToOneField(blank=True, help_text='When set, auto-created for the source pond of that pond-to-pond transfer (selling pond).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biomass_sample_out', to='api.aquaculturefishpondtransfer'),
        ),
        migrations.AddField(
            model_name='aquaculturebiomasssample',
            name='source_fish_pond_transfer_line',
            field=models.OneToOneField(blank=True, help_text='When set, auto-created for the destination pond of that transfer line (buying pond).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biomass_sample_in', to='api.aquaculturefishpondtransferline'),
        ),
    ]
