# Generated by Django 5.2.15 on 2026-08-20 04:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0170_aquaculture_auto_biomass_sample_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='aquaculturefishpondtransferline',
            name='price_basis',
            field=models.TextField(blank=True, help_text='How this line was priced (cost per kg, margin applied, or manual override).'),
        ),
        migrations.AddField(
            model_name='aquaculturefishpondtransferline',
            name='sale_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text="sale_rate_per_kg x weight_kg — what the buying pond capitalizes. The difference from cost_amount is the selling pond's margin, eliminated from company profit on consolidation.", max_digits=14),
        ),
        migrations.AddField(
            model_name='aquaculturefishpondtransferline',
            name='sale_rate_per_kg',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="Internal sale price per kg charged to the buying pond (cost per kg + the company's inter-pond margin, unless entered by hand).", max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='aquaculture_internal_transfer_margin_per_kg',
            field=models.DecimalField(decimal_places=4, default=Decimal('20'), help_text="Margin per kg the selling pond earns when fish move to another pond: the internal sale price is that line's cost per kg plus this (cost 100/kg with margin 20 sells at 120/kg). Applies to inter-pond transfers only — a genuine sale to an outside customer keeps the price that customer paid. Set to 0 to move fish at cost, as before.", max_digits=14),
        ),
    ]
