# Generated by Django 5.2.15 on 2026-08-20 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0171_aquaculture_internal_transfer_margin'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='internal_fish_transfer_line',
            field=models.OneToOneField(blank=True, help_text="When set, this document is the paper record of one inter-pond fish transfer line (pond buying from pond). Its economics are carried by the transfer's own journal (1581/4245/5245), so it never posts GL, never receives stock, and never ages in A/R or A/P — it is evidence of the internal purchase, settled through the inter-pond current account rather than in cash.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_purchase_bill', to='api.aquaculturefishpondtransferline'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='internal_fish_transfer_line',
            field=models.OneToOneField(blank=True, help_text="When set, this document is the paper record of one inter-pond fish transfer line (pond selling to pond). Its economics are carried by the transfer's own journal (1581/4245/5245), so it never posts GL, never receives stock, and never ages in A/R or A/P — it is evidence of the internal sale, settled through the inter-pond current account rather than in cash.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_sale_invoice', to='api.aquaculturefishpondtransferline'),
        ),
    ]
