# Generated by Django 5.2.15 on 2026-08-20 05:27

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0172_inter_pond_trade_documents'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.AlterModelManagers(
            name='bill',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='invoice',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
