# Generated by Django 5.2.15 on 2026-08-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0173_internal_trade_document_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='books_locked_through',
            field=models.DateField(blank=True, help_text='Accounting period close: general-ledger activity dated on or before this day is final. Posting, editing, unposting, or deleting anything that hits the GL on or before it is refused, so statements already issued for those periods cannot change. Blank = open books.', null=True),
        ),
    ]
