# Generated by Django 5.2.15 on 2026-09-10 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0180_mill_truck_transport_and_scheme_reserve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentryline',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='api.chartofaccount'),
        ),
    ]
