# Generated by Django 5.2.15 on 2026-09-10 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0188_invoice_idempotency_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('entity_type', models.CharField(db_index=True, max_length=64)),
                ('entity_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('entity_ref', models.CharField(blank=True, default='', max_length=128)),
                ('reason', models.TextField(blank=True, default='')),
                ('before_json', models.JSONField(blank=True, default=dict)),
                ('after_json', models.JSONField(blank=True, default=dict)),
                ('request_meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'financial_audit_event',
            },
        ),
        migrations.AddField(
            model_name='meter',
            name='max_reading',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Highest display value before the register rolls to zero. Null = no rollover (open-ended totalizer).', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='dispenser',
            name='island',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispensers', to='api.island'),
        ),
        migrations.AlterField(
            model_name='employeeledgerentry',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='api.employee'),
        ),
        migrations.AlterField(
            model_name='island',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='islands', to='api.station'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='dispenser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meters', to='api.dispenser'),
        ),
        migrations.AlterField(
            model_name='nozzle',
            name='meter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nozzles', to='api.meter'),
        ),
        migrations.AlterField(
            model_name='nozzle',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nozzles', to='api.item'),
        ),
        migrations.AlterField(
            model_name='nozzle',
            name='tank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nozzles', to='api.tank'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['company', 'bill_date'], name='bill_company_date_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['company', 'status', 'bill_date'], name='bill_company_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['company', 'vendor', 'bill_date'], name='bill_company_vend_date_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['company', 'invoice_date'], name='inv_company_date_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['company', 'status', 'invoice_date'], name='inv_company_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['company', 'customer', 'invoice_date'], name='inv_company_cust_date_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['company', 'payment_date'], name='pay_company_date_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['company', 'payment_type', 'payment_date'], name='pay_company_type_date_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['company', 'customer', 'payment_date'], name='pay_company_cust_date_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['company', 'vendor', 'payment_date'], name='pay_company_vend_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0), ('subtotal__gte', 0), ('tax_total__gte', 0)), name='bill_nonneg_amounts'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('customer_number__gt', '')), fields=('company', 'customer_number'), name='customer_company_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(('employee_code__gt', '')), fields=('company', 'employee_code'), name='employee_company_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0), ('subtotal__gte', 0), ('tax_total__gte', 0)), name='invoice_nonneg_amounts'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('item_number__gt', '')), fields=('company', 'item_number'), name='item_company_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='journalentryline',
            constraint=models.CheckConstraint(condition=models.Q(('debit__gte', 0), ('credit__gte', 0)), name='jel_nonneg_debit_credit'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='payment_nonneg_amount'),
        ),
        migrations.AddConstraint(
            model_name='station',
            constraint=models.UniqueConstraint(condition=models.Q(('station_number__gt', '')), fields=('company', 'station_number'), name='station_company_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.UniqueConstraint(condition=models.Q(('vendor_number__gt', '')), fields=('company', 'vendor_number'), name='vendor_company_number_uniq'),
        ),
        migrations.AddField(
            model_name='financialauditevent',
            name='actor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_audit_events', to='api.user'),
        ),
        migrations.AddField(
            model_name='financialauditevent',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_audit_events', to='api.company'),
        ),
        migrations.AddIndex(
            model_name='financialauditevent',
            index=models.Index(fields=['company', 'created_at'], name='fae_company_created_idx'),
        ),
        migrations.AddIndex(
            model_name='financialauditevent',
            index=models.Index(fields=['company', 'entity_type', 'entity_id'], name='fae_company_entity_idx'),
        ),
    ]
