# Generated by Django 5.2.15 on 2026-09-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0193_mill_transport_per_ton_cleanup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='actual_lorry_fare',
            field=models.DecimalField(decimal_places=2, default=0, help_text='What we paid the driver for this load (total = tons × ৳/ton entered on the bill).', max_digits=14),
        ),
        migrations.AlterField(
            model_name='bill',
            name='mill_settlement',
            field=models.CharField(blank=True, default='', help_text='credit = net after discount+lorry stays on A/P; cash = credit limit full, pay that same net by bank/cash now.', max_length=16),
        ),
        migrations.AlterField(
            model_name='bill',
            name='truck_transport_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Mill's fixed lorry share for this load (rate card). Applied now only on cash-only mill bills.", max_digits=14),
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='rate',
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
        migrations.AlterField(
            model_name='vendorratecard',
            name='transport_percent',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Transport allowance as % of line MRP (qty×MRP). Stacks with per-unit/kg/ton when set.', max_digits=8),
        ),
    ]
