# Generated by Django 6.1.1 on 2026-09-25 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0199_aqua_day_log_harvest_plan_withdrawal'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aquacultureexpense',
            new_name='aq_exp_clear_sell_idx',
            old_name='aquaculture_company_5f0c1a_idx',
        ),
        migrations.RenameIndex(
            model_name='aquacultureharvestlotplan',
            new_name='aq_harvest_status_idx',
            old_name='aquaculture_harvest_status_idx',
        ),
        migrations.RenameIndex(
            model_name='aquacultureharvestlotplan',
            new_name='aq_harvest_pond_idx',
            old_name='aquaculture_harvest_pond_idx',
        ),
        migrations.RenameIndex(
            model_name='aquacultureponddaylog',
            new_name='aq_daylog_date_idx',
            old_name='aquaculture_company_daylog_idx',
        ),
        migrations.RenameIndex(
            model_name='aquacultureponddaylog',
            new_name='aq_daylog_pond_date_idx',
            old_name='aquaculture_company_pond_day_idx',
        ),
    ]
