from fastapi import APIRouter
from app.api.v1 import auth, tenants, items, warehouses, suppliers, customers, purchase, sales, inventory, manufacturing, livestock, transport, fuel, accounting, accounting_reports, operational_reports, payroll, feed_manufacturing, platform, tenant_settings, tenant_announcements, preformulations, dashboard, crm, expense_claims, business_cards, loans, hr, workshop, lab, lc, cost_centers, requisitions

api_router = APIRouter()

api_router.include_router(platform.router, prefix="/platform", tags=["platform"])
api_router.include_router(dashboard.router, prefix="/dashboard", tags=["dashboard"])
api_router.include_router(auth.router, prefix="/auth", tags=["auth"])
api_router.include_router(tenants.router, prefix="/tenants", tags=["tenants"])
api_router.include_router(tenant_settings.router, prefix="", tags=["tenant-settings"])
api_router.include_router(tenant_announcements.router, prefix="", tags=["tenant-announcements"])
api_router.include_router(items.router, prefix="/items", tags=["items"])
api_router.include_router(warehouses.router, prefix="/warehouses", tags=["warehouses"])
api_router.include_router(inventory.router, prefix="/inventory", tags=["inventory"])
api_router.include_router(suppliers.router, prefix="/suppliers", tags=["suppliers"])
api_router.include_router(customers.router, prefix="/customers", tags=["customers"])
api_router.include_router(purchase.router, prefix="/purchase", tags=["purchase"])
api_router.include_router(requisitions.router, prefix="/requisitions", tags=["requisitions"])
api_router.include_router(sales.router, prefix="/sales", tags=["sales"])
api_router.include_router(manufacturing.router, prefix="/manufacturing", tags=["manufacturing"])
api_router.include_router(feed_manufacturing.router, prefix="/feed", tags=["feed-manufacturing"])
api_router.include_router(preformulations.router, prefix="", tags=["pre-formulations"])
api_router.include_router(crm.router, prefix="/crm", tags=["crm"])
api_router.include_router(expense_claims.router, prefix="/expenses", tags=["expenses"])
api_router.include_router(business_cards.router, prefix="/cards", tags=["business-cards"])
api_router.include_router(livestock.router, prefix="/livestock", tags=["livestock"])
api_router.include_router(transport.router, prefix="/transport", tags=["transport"])
api_router.include_router(fuel.router, prefix="/fuel", tags=["fuel"])
api_router.include_router(cost_centers.router, prefix="/cost-centers", tags=["cost-centers"])
api_router.include_router(accounting.router, prefix="/accounting", tags=["accounting"])
api_router.include_router(accounting_reports.router, prefix="/accounting", tags=["accounting"])
api_router.include_router(operational_reports.router, prefix="/reports", tags=["reports"])
api_router.include_router(payroll.router, prefix="/payroll", tags=["payroll"])
api_router.include_router(loans.router, prefix="/loans", tags=["loans"])
api_router.include_router(hr.router, prefix="/hr", tags=["hr"])
api_router.include_router(workshop.router, prefix="/workshop", tags=["workshop"])
api_router.include_router(lab.router, prefix="/lab", tags=["lab"])
api_router.include_router(lc.router, prefix="/lc", tags=["letter-of-credit"])
