"""add_feed_manufacturing_tables

Revision ID: af2b4b819804
Revises: 
Create Date: 2025-12-16 10:30:13.030787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af2b4b819804'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed_products',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('subtype', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('pellet_size_mm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('packaging', sa.String(), nullable=True),
    sa.Column('target_protein_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('target_fat_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('target_fiber_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('target_moisture_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('target_ash_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('target_energy_kcal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('requires_grinding', sa.Boolean(), nullable=True),
    sa.Column('requires_extrusion', sa.Boolean(), nullable=True),
    sa.Column('requires_pelleting', sa.Boolean(), nullable=True),
    sa.Column('requires_drying', sa.Boolean(), nullable=True),
    sa.Column('requires_coating', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feed_products_id'), 'feed_products', ['id'], unique=False)
    op.create_index(op.f('ix_feed_products_item_id'), 'feed_products', ['item_id'], unique=True)
    op.create_index(op.f('ix_feed_products_tenant_id'), 'feed_products', ['tenant_id'], unique=False)
    op.create_table('ingredients',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_type', sa.String(), nullable=False),
    sa.Column('cost_method', sa.String(), nullable=True),
    sa.Column('protein_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fat_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fiber_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ash_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('moisture_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('energy_kcal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_premix', sa.Boolean(), nullable=True),
    sa.Column('premix_unit', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredients_id'), 'ingredients', ['id'], unique=False)
    op.create_index(op.f('ix_ingredients_item_id'), 'ingredients', ['item_id'], unique=True)
    op.create_index(op.f('ix_ingredients_tenant_id'), 'ingredients', ['tenant_id'], unique=False)
    op.create_table('feed_boms',
    sa.Column('bom_code', sa.String(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=True),
    sa.Column('effective_to', sa.DateTime(), nullable=True),
    sa.Column('default_batch_size_ton', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('process_type', sa.String(), nullable=False),
    sa.Column('pellet_size_mm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_floating', sa.Boolean(), nullable=True),
    sa.Column('target_protein_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('target_fat_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('target_fiber_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('target_moisture_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('target_ash_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['feed_products.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feed_boms_bom_code'), 'feed_boms', ['bom_code'], unique=False)
    op.create_index(op.f('ix_feed_boms_id'), 'feed_boms', ['id'], unique=False)
    op.create_index(op.f('ix_feed_boms_product_id'), 'feed_boms', ['product_id'], unique=False)
    op.create_index(op.f('ix_feed_boms_tenant_id'), 'feed_boms', ['tenant_id'], unique=False)
    op.create_table('feed_bom_lines',
    sa.Column('bom_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('inclusion_basis', sa.String(), nullable=False),
    sa.Column('inclusion_value', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('computed_kg', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('computed_percent', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('loss_factor_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('phase', sa.String(), nullable=True),
    sa.Column('min_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('max_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bom_id'], ['feed_boms.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feed_bom_lines_bom_id'), 'feed_bom_lines', ['bom_id'], unique=False)
    op.create_index(op.f('ix_feed_bom_lines_id'), 'feed_bom_lines', ['id'], unique=False)
    op.create_index(op.f('ix_feed_bom_lines_tenant_id'), 'feed_bom_lines', ['tenant_id'], unique=False)
    op.create_table('production_orders',
    sa.Column('order_number', sa.String(), nullable=False),
    sa.Column('bom_id', sa.Integer(), nullable=False),
    sa.Column('batch_size_ton', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('batch_size_kg', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('planned_date', sa.DateTime(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('planned_output_kg', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('actual_output_kg', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('yield_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('material_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('overhead_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('cost_per_kg', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bom_id'], ['feed_boms.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_orders_bom_id'), 'production_orders', ['bom_id'], unique=False)
    op.create_index(op.f('ix_production_orders_id'), 'production_orders', ['id'], unique=False)
    op.create_index(op.f('ix_production_orders_order_number'), 'production_orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_production_orders_tenant_id'), 'production_orders', ['tenant_id'], unique=False)
    op.create_table('batch_qc_results',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('actual_protein_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('actual_fat_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('actual_fiber_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('actual_moisture_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('actual_ash_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('actual_energy_kcal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('protein_pass', sa.Boolean(), nullable=True),
    sa.Column('fat_pass', sa.Boolean(), nullable=True),
    sa.Column('fiber_pass', sa.Boolean(), nullable=True),
    sa.Column('moisture_pass', sa.Boolean(), nullable=True),
    sa.Column('ash_pass', sa.Boolean(), nullable=True),
    sa.Column('energy_pass', sa.Boolean(), nullable=True),
    sa.Column('overall_pass', sa.Boolean(), nullable=True),
    sa.Column('test_date', sa.DateTime(), nullable=True),
    sa.Column('tested_by', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['production_orders.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_qc_results_id'), 'batch_qc_results', ['id'], unique=False)
    op.create_index(op.f('ix_batch_qc_results_order_id'), 'batch_qc_results', ['order_id'], unique=True)
    op.create_index(op.f('ix_batch_qc_results_tenant_id'), 'batch_qc_results', ['tenant_id'], unique=False)
    op.create_table('production_order_lines',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('bom_line_id', sa.Integer(), nullable=True),
    sa.Column('required_qty_kg', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('required_qty_with_loss_kg', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('consumed_qty_kg', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bom_line_id'], ['feed_bom_lines.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['production_orders.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_order_lines_id'), 'production_order_lines', ['id'], unique=False)
    op.create_index(op.f('ix_production_order_lines_order_id'), 'production_order_lines', ['order_id'], unique=False)
    op.create_index(op.f('ix_production_order_lines_tenant_id'), 'production_order_lines', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_production_order_lines_tenant_id'), table_name='production_order_lines')
    op.drop_index(op.f('ix_production_order_lines_order_id'), table_name='production_order_lines')
    op.drop_index(op.f('ix_production_order_lines_id'), table_name='production_order_lines')
    op.drop_table('production_order_lines')
    op.drop_index(op.f('ix_batch_qc_results_tenant_id'), table_name='batch_qc_results')
    op.drop_index(op.f('ix_batch_qc_results_order_id'), table_name='batch_qc_results')
    op.drop_index(op.f('ix_batch_qc_results_id'), table_name='batch_qc_results')
    op.drop_table('batch_qc_results')
    op.drop_index(op.f('ix_production_orders_tenant_id'), table_name='production_orders')
    op.drop_index(op.f('ix_production_orders_order_number'), table_name='production_orders')
    op.drop_index(op.f('ix_production_orders_id'), table_name='production_orders')
    op.drop_index(op.f('ix_production_orders_bom_id'), table_name='production_orders')
    op.drop_table('production_orders')
    op.drop_index(op.f('ix_feed_bom_lines_tenant_id'), table_name='feed_bom_lines')
    op.drop_index(op.f('ix_feed_bom_lines_id'), table_name='feed_bom_lines')
    op.drop_index(op.f('ix_feed_bom_lines_bom_id'), table_name='feed_bom_lines')
    op.drop_table('feed_bom_lines')
    op.drop_index(op.f('ix_feed_boms_tenant_id'), table_name='feed_boms')
    op.drop_index(op.f('ix_feed_boms_product_id'), table_name='feed_boms')
    op.drop_index(op.f('ix_feed_boms_id'), table_name='feed_boms')
    op.drop_index(op.f('ix_feed_boms_bom_code'), table_name='feed_boms')
    op.drop_table('feed_boms')
    op.drop_index(op.f('ix_ingredients_tenant_id'), table_name='ingredients')
    op.drop_index(op.f('ix_ingredients_item_id'), table_name='ingredients')
    op.drop_index(op.f('ix_ingredients_id'), table_name='ingredients')
    op.drop_table('ingredients')
    op.drop_index(op.f('ix_feed_products_tenant_id'), table_name='feed_products')
    op.drop_index(op.f('ix_feed_products_item_id'), table_name='feed_products')
    op.drop_index(op.f('ix_feed_products_id'), table_name='feed_products')
    op.drop_table('feed_products')
    # ### end Alembic commands ###

