"""add_platform_models

Revision ID: e0b0bac3501c
Revises: af2b4b819804
Create Date: 2025-12-16 11:22:02.816356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0b0bac3501c'
down_revision = 'af2b4b819804'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

